export const BigUnits = ['איילון', 'דן', 'דרום', 'דרור', 'החוף', 'החורש', 'הצוק', 'השחר', 'חיפה', 'יהודה', 'ירושלים', 'צפון', 'רמת גן', 'שורק', 'תל אביב יפו']

export const tribes = [
    {'hanaga': 'איילון', 'shevet': 'אופק'},
    {'hanaga': 'איילון', 'shevet': 'אחווה'}, 
    {'hanaga': 'איילון', 'shevet': 'אייל'},
    {'hanaga': 'איילון', 'shevet': 'איתן'},
    {'hanaga': 'איילון', 'shevet': 'אמיר'},
    {'hanaga': 'איילון', 'shevet': 'ארבל'},
    {'hanaga': 'איילון', 'shevet': 'אתגר'}, 
    {'hanaga': 'איילון', 'shevet': 'דגן'},
    {'hanaga': 'איילון', 'shevet': 'דרור'}, 
    {'hanaga': 'איילון', 'shevet': 'יובל'}, 
    {'hanaga': 'איילון', 'shevet': 'לביא'}, 
    {'hanaga': 'איילון', 'shevet': 'להב'}, 
    {'hanaga': 'איילון', 'shevet': 'לפיד'}, 
    {'hanaga': 'איילון', 'shevet': 'נגה'}, 
    {'hanaga': 'איילון', 'shevet': 'ניר'}, 
    {'hanaga': 'איילון', 'shevet': 'נעלה'}, 
    {'hanaga': 'איילון', 'shevet': 'סופה'}, 
    {'hanaga': 'איילון', 'shevet': 'עמית'}, 
    {'hanaga': 'איילון', 'shevet': 'ראם'}, 
    {'hanaga': 'איילון', 'shevet': 'רעות'}, 
    {'hanaga': 'איילון', 'shevet': 'תבור'},  
    {'hanaga': 'דן', 'shevet': 'און'}, 
    {'hanaga': 'דן', 'shevet': 'ברק'}, 
    {'hanaga': 'דן', 'shevet': 'גבעתיים'}, 
    {'hanaga': 'דן', 'shevet': 'גלעד'}, 
    {'hanaga': 'דן', 'shevet': 'גנים'}, 
    {'hanaga': 'דן', 'shevet': 'דור'}, 
    {'hanaga': 'דן', 'shevet': 'המושבה'}, 
    {'hanaga': 'דן', 'shevet': 'להב'}, 
    {'hanaga': 'דן', 'shevet': 'מגן'}, 
    {'hanaga': 'דן', 'shevet': 'עוגן'}, 
    {'hanaga': 'דן', 'shevet': 'עוז'}, 
    {'hanaga': 'דן', 'shevet': 'ראשונים'},  
    {'hanaga': 'דרום', 'shevet': 'אדם'}, 
    {'hanaga': 'דרום', 'shevet': 'אדר'}, 
    {'hanaga': 'דרום', 'shevet': 'אופק'}, 
    {'hanaga': 'דרום', 'shevet': 'איתן'}, 
    {'hanaga': 'דרום', 'shevet': 'אשל'}, 
    {'hanaga': 'דרום', 'shevet': 'במדבר'}, 
    {'hanaga': 'דרום', 'shevet': 'חצרים'}, 
    {'hanaga': 'דרום', 'shevet': 'יואב'}, 
    {'hanaga': 'דרום', 'shevet': 'מצדה'}, 
    {'hanaga': 'דרום', 'shevet': 'נגב'}, 
    {'hanaga': 'דרום', 'shevet': 'נועם'}, 
    {'hanaga': 'דרום', 'shevet': 'נופר'}, 
    {'hanaga': 'דרום', 'shevet': 'ניצני הנגב'}, 
    {'hanaga': 'דרום', 'shevet': 'נמרוד'}, 
    {'hanaga': 'דרום', 'shevet': 'סיני'}, 
    {'hanaga': 'דרום', 'shevet': 'ערבה'}, 
    {'hanaga': 'דרום', 'shevet': 'צוק'}, 
    {'hanaga': 'דרום', 'shevet': 'צחור'}, 
    {'hanaga': 'דרום', 'shevet': 'רכסים'}, 
    {'hanaga': 'דרום', 'shevet': 'שגיא'}, 
    {'hanaga': 'דרום', 'shevet': 'שמשון'}, 
    {'hanaga': 'דרום', 'shevet': 'שקד'},  
    {'hanaga': 'דרור', 'shevet': 'בזק'}, 
    {'hanaga': 'דרור', 'shevet': 'בן יהודה'}, 
    {'hanaga': 'דרור', 'shevet': 'לביא'}, 
    {'hanaga': 'דרור', 'shevet': 'סירונית'}, 
    {'hanaga': 'דרור', 'shevet': 'פולג'}, 
    {'hanaga': 'דרור', 'shevet': 'רגבים'}, 
    {'hanaga': 'דרור', 'shevet': 'רמון'}, 
    {'hanaga': 'דרור', 'shevet': 'תמיד'},  
    {'hanaga': 'החוף', 'shevet': 'איתן'}, 
    {'hanaga': 'החוף', 'shevet': 'ארבל'}, 
    {'hanaga': 'החוף', 'shevet': 'ארנון'}, 
    {'hanaga': 'החוף', 'shevet': 'דן'}, 
    {'hanaga': 'החוף', 'shevet': 'הסלע צופי ים'}, 
    {'hanaga': 'החוף', 'shevet': 'יהודה'}, 
    {'hanaga': 'החוף', 'shevet': 'יעד'}, 
    {'hanaga': 'החוף', 'shevet': 'כנען'}, 
    {'hanaga': 'החוף', 'shevet': 'מכבים'}, 
    {'hanaga': 'החוף', 'shevet': 'משואות'}, 
    {'hanaga': 'החוף', 'shevet': 'מתן'}, 
    {'hanaga': 'החוף', 'shevet': 'עומר'}, 
    {'hanaga': 'החוף', 'shevet': 'עתיד'}, 
    {'hanaga': 'החוף', 'shevet': 'רעם'}, 
    {'hanaga': 'החוף', 'shevet': 'שורק'}, 
    {'hanaga': 'החוף', 'shevet': 'שקמה'},  
    {'hanaga': 'החורש', 'shevet': 'אילן'}, 
    {'hanaga': 'החורש', 'shevet': 'אלומות'}, 
    {'hanaga': 'החורש', 'shevet': 'אלון'}, 
    {'hanaga': 'החורש', 'shevet': 'אלמוג'}, 
    {'hanaga': 'החורש', 'shevet': 'בני היער'}, 
    {'hanaga': 'החורש', 'shevet': 'גולן'}, 
    {'hanaga': 'החורש', 'shevet': 'גפן'}, 
    {'hanaga': 'החורש', 'shevet': 'החלוץ'}, 
    {'hanaga': 'החורש', 'shevet': 'מגל'}, 
    {'hanaga': 'החורש', 'shevet': 'עומר'}, 
    {'hanaga': 'החורש', 'shevet': 'פלג'}, 
    {'hanaga': 'החורש', 'shevet': 'צוקים'}, 
    {'hanaga': 'החורש', 'shevet': 'שקד'},  
    {'hanaga': 'הצוק', 'shevet': 'איתן'}, 
    {'hanaga': 'הצוק', 'shevet': 'ארד'}, 
    {'hanaga': 'הצוק', 'shevet': 'געש'}, 
    {'hanaga': 'הצוק', 'shevet': 'דקר'}, 
    {'hanaga': 'הצוק', 'shevet': 'הרצל'}, 
    {'hanaga': 'הצוק', 'shevet': 'נוה מגן'}, 
    {'hanaga': 'הצוק', 'shevet': 'ני"ר'}, 
    {'hanaga': 'הצוק', 'shevet': 'סער'}, 
    {'hanaga': 'הצוק', 'shevet': 'רשפים'}, 
    {'hanaga': 'הצוק', 'shevet': 'שחף'},  
    {'hanaga': 'השחר', 'shevet': 'אופק'}, 
    {'hanaga': 'השחר', 'shevet': 'אפיק'}, 
    {'hanaga': 'השחר', 'shevet': 'גלבוע'}, 
    {'hanaga': 'השחר', 'shevet': 'הדר'}, 
    {'hanaga': 'השחר', 'shevet': 'הראל'}, 
    {'hanaga': 'השחר', 'shevet': 'נבו'}, 
    {'hanaga': 'השחר', 'shevet': 'נחשון'}, 
    {'hanaga': 'השחר', 'shevet': 'עמירים'}, 
    {'hanaga': 'השחר', 'shevet': 'צור'}, 
    {'hanaga': 'השחר', 'shevet': 'רכ"ס'}, 
    {'hanaga': 'השחר', 'shevet': 'שליט'},  
    {'hanaga': 'חיפה', 'shevet': 'אורן'}, 
    {'hanaga': 'חיפה', 'shevet': 'אילנות'}, 
    {'hanaga': 'חיפה', 'shevet': 'אפיק'}, 
    {'hanaga': 'חיפה', 'shevet': 'גלים'}, 
    {'hanaga': 'חיפה', 'shevet': 'דרור'}, 
    {'hanaga': 'חיפה', 'shevet': 'העגן'}, 
    {'hanaga': 'חיפה', 'shevet': 'חופים'}, 
    {'hanaga': 'חיפה', 'shevet': 'כרמל'}, 
    {'hanaga': 'חיפה', 'shevet': 'לטם'}, 
    {'hanaga': 'חיפה', 'shevet': 'מגשים'}, 
    {'hanaga': 'חיפה', 'shevet': 'משוטטים'}, 
    {'hanaga': 'חיפה', 'shevet': 'נשרים'}, 
    {'hanaga': 'חיפה', 'shevet': 'עמית'}, 
    {'hanaga': 'חיפה', 'shevet': 'צופי ים חיפה'}, 
    {'hanaga': 'חיפה', 'shevet': 'צופית'}, 
    {'hanaga': 'חיפה', 'shevet': 'תדהר'},  
    {'hanaga': 'יהודה', 'shevet': 'אופק'}, 
    {'hanaga': 'יהודה', 'shevet': 'איתן'}, 
    {'hanaga': 'יהודה', 'shevet': 'אליאב'}, 
    {'hanaga': 'יהודה', 'shevet': 'דקר'}, 
    {'hanaga': 'יהודה', 'shevet': 'האלה'}, 
    {'hanaga': 'יהודה', 'shevet': 'הראל'}, 
    {'hanaga': 'יהודה', 'shevet': 'זאב'}, 
    {'hanaga': 'יהודה', 'shevet': 'יהודה'}, 
    {'hanaga': 'יהודה', 'shevet': 'יונתן'}, 
    {'hanaga': 'יהודה', 'shevet': 'לביא'}, 
    {'hanaga': 'יהודה', 'shevet': 'ערבה'}, 
    {'hanaga': 'יהודה', 'shevet': 'פסגות'}, 
    {'hanaga': 'יהודה', 'shevet': 'רועי'}, 
    {'hanaga': 'יהודה', 'shevet': 'שוב"ל'}, 
    {'hanaga': 'יהודה', 'shevet': 'שורק'}, 
    {'hanaga': 'יהודה', 'shevet': 'תמיר'},  
    {'hanaga': 'ירושלים', 'shevet': 'אלעד'}, 
    {'hanaga': 'ירושלים', 'shevet': 'אמיר'}, 
    {'hanaga': 'ירושלים', 'shevet': 'אריאל'}, 
    {'hanaga': 'ירושלים', 'shevet': 'בית הכרם'}, 
    {'hanaga': 'ירושלים', 'shevet': 'היובל'}, 
    {'hanaga': 'ירושלים', 'shevet': 'העומר'}, 
    {'hanaga': 'ירושלים', 'shevet': 'הר חומה'}, 
    {'hanaga': 'ירושלים', 'shevet': 'זוהר'}, 
    {'hanaga': 'ירושלים', 'shevet': 'להבות'}, 
    {'hanaga': 'ירושלים', 'shevet': 'מודיעין'}, 
    {'hanaga': 'ירושלים', 'shevet': 'מצדה'}, 
    {'hanaga': 'ירושלים', 'shevet': 'משואות'}, 
    {'hanaga': 'ירושלים', 'shevet': 'עוז'}, 
    {'hanaga': 'ירושלים', 'shevet': 'קטמונים'}, 
    {'hanaga': 'ירושלים', 'shevet': 'רכסים'}, 
    {'hanaga': 'צפון', 'shevet': 'ים'}, 
    {'hanaga': 'צפון', 'shevet': 'אדיס'}, 
    {'hanaga': 'צפון', 'shevet': 'איריס'}, 
    {'hanaga': 'צפון', 'shevet': 'אלון'}, 
    {'hanaga': 'צפון', 'shevet': 'אשחר'}, 
    {'hanaga': 'צפון', 'shevet': 'גונן'}, 
    {'hanaga': 'צפון', 'shevet': 'גלעד'}, 
    {'hanaga': 'צפון', 'shevet': 'יבנאל'}, 
    {'hanaga': 'צפון', 'shevet': 'יזרעאל'}, 
    {'hanaga': 'צפון', 'shevet': 'כנרת צופי ים'}, 
    {'hanaga': 'צפון', 'shevet': 'כרם'}, 
    {'hanaga': 'צפון', 'shevet': 'לביא'}, 
    {'hanaga': 'צפון', 'shevet': 'להבות'}, 
    {'hanaga': 'צפון', 'shevet': 'מעיינות'}, 
    {'hanaga': 'צפון', 'shevet': 'עידן'}, 
    {'hanaga': 'צפון', 'shevet': 'עמיחי'}, 
    {'hanaga': 'צפון', 'shevet': 'עפר'}, 
    {'hanaga': 'צפון', 'shevet': 'שחר'}, 
    {'hanaga': 'צפון', 'shevet': 'שלהבת'}, 
    {'hanaga': 'צפון', 'shevet': 'עונות'}, 
    {'hanaga': 'צפון', 'shevet': 'רועי'}, 
    {'hanaga': 'רמת גן', 'shevet': 'אילת'}, 
    {'hanaga': 'רמת גן', 'shevet': 'אפעל'}, 
    {'hanaga': 'רמת גן', 'shevet': 'ירדן'}, 
    {'hanaga': 'רמת גן', 'shevet': 'ירקון'}, 
    {'hanaga': 'רמת גן', 'shevet': 'עלית'}, 
    {'hanaga': 'רמת גן', 'shevet': 'רמת גן'}, 
    {'hanaga': 'רמת גן', 'shevet': 'רמת חן'}, 
    {'hanaga': 'רמת גן', 'shevet': 'רעים'}, 
    {'hanaga': 'רמת גן', 'shevet': 'שקמה'},  
    {'hanaga': 'שורק', 'shevet': 'אביב'}, 
    {'hanaga': 'שורק', 'shevet': 'איתן'}, 
    {'hanaga': 'שורק', 'shevet': 'אריות'}, 
    {'hanaga': 'שורק', 'shevet': 'גיא'}, 
    {'hanaga': 'שורק', 'shevet': 'דותן'}, 
    {'hanaga': 'שורק', 'shevet': 'הנחל'}, 
    {'hanaga': 'שורק', 'shevet': 'יאיר'}, 
    {'hanaga': 'שורק', 'shevet': 'ירדן'}, 
    {'hanaga': 'שורק', 'shevet': 'כפיר'}, 
    {'hanaga': 'שורק', 'shevet': 'מידב'}, 
    {'hanaga': 'שורק', 'shevet': 'סהר'}, 
    {'hanaga': 'שורק', 'shevet': 'סער'}, 
    {'hanaga': 'שורק', 'shevet': 'עידן'}, 
    {'hanaga': 'שורק', 'shevet': 'ראם'}, 
    {'hanaga': 'שורק', 'shevet': 'רעות'}, 
    {'hanaga': 'שורק', 'shevet': 'שחר'}, 
    {'hanaga': 'שורק', 'shevet': 'שלהבות'}, 
    {'hanaga': 'שורק', 'shevet': 'שני"ר'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'אביב'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'אופק'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'איתן'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'בית דני'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'דיזנגוף'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'דן'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'הגבעה'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'החורש'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'הנשיא'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'הצוק'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'חורב'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'חצב'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'יפו'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'כפיר'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'צבר'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'צהלה'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'צופי ים יפו'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'צופי ים תל אביב'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'קהילה'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': "רמת אביב ג'"}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'רעות'}
]
