export const BigUnits = ['איילון', 'דן', 'דרום', 'דרור', 'החוף', 'החורש', 'הצוק', 'השחר', 'חיפה', 'יהודה', 'ירושלים', 'צפון', 'רמת גן', 'שורק', 'תל אביב יפו']






export const tribes = [
    {'hanaga': 'איילון', 'shevet': 'אופק','code':'xRRd3S'},
    {'hanaga': 'איילון', 'shevet': 'אחווה','code':'byJNDx'}, 
    {'hanaga': 'איילון', 'shevet': 'אייל','code':'EnN7Me'},
    {'hanaga': 'איילון', 'shevet': 'איתן','code':'TKUxAL'},
    {'hanaga': 'איילון', 'shevet': 'אמיר','code':'PDV8rx'},
    {'hanaga': 'איילון', 'shevet': 'ארבל','code':'e7aJ2e'},
    {'hanaga': 'איילון', 'shevet': 'אתגר','code':'ZzaHuz'}, 
    {'hanaga': 'איילון', 'shevet': 'דגן','code':'IpM7Bi'},
    {'hanaga': 'איילון', 'shevet': 'דרור','code':'WTnMHx'}, 
    {'hanaga': 'איילון', 'shevet': 'יובל','code':'f5631d'}, 
    {'hanaga': 'איילון', 'shevet': 'לביא','code':'bS6uha'}, 
    {'hanaga': 'איילון', 'shevet': 'להב','code':'ng3bIt'}, 
    {'hanaga': 'איילון', 'shevet': 'לפיד','code':'p7VI69'}, 
    {'hanaga': 'איילון', 'shevet': 'נגה','code':'qymZS4'}, 
    {'hanaga': 'איילון', 'shevet': 'ניר','code':'AlgbfO'}, 
    {'hanaga': 'איילון', 'shevet': 'נעלה','code':'N6CDE5'}, 
    {'hanaga': 'איילון', 'shevet': 'סופה','code':'s8oD7b'}, 
    {'hanaga': 'איילון', 'shevet': 'עמית','code':'KNpyOs'}, 
    {'hanaga': 'איילון', 'shevet': 'ראם','code':'jvBbht'}, 
    {'hanaga': 'איילון', 'shevet': 'רעות','code':'6OEMoY'}, 
    {'hanaga': 'איילון', 'shevet': 'תבור','code':'H2eWkO'},  
    {'hanaga': 'דן', 'shevet': 'און','code':'nZuMzI'}, 
    {'hanaga': 'דן', 'shevet': 'ברק','code':'4afxOa'}, 
    {'hanaga': 'דן', 'shevet': 'גבעתיים','code':'pnZO4m'}, 
    {'hanaga': 'דן', 'shevet': 'גלעד','code':'PRymY5'}, 
    {'hanaga': 'דן', 'shevet': 'גנים','code':'Bq8SGp'}, 
    {'hanaga': 'דן', 'shevet': 'דור','code':'PCBJd6'}, 
    {'hanaga': 'דן', 'shevet': 'המושבה','code':'bRAaUv'}, 
    {'hanaga': 'דן', 'shevet': 'להב','code':'qtfP77'}, 
    {'hanaga': 'דן', 'shevet': 'מגן','code':'QnMTrS'}, 
    {'hanaga': 'דן', 'shevet': 'עוגן','code':'LQUGm4'}, 
    {'hanaga': 'דן', 'shevet': 'עוז','code':'KnUy1N'}, 
    {'hanaga': 'דן', 'shevet': 'ראשונים','code':'JVm90C'},  
    {'hanaga': 'דרום', 'shevet': 'אדם','code':'KP09AF'}, 
    {'hanaga': 'דרום', 'shevet': 'אדר','code':'oL1FSZ'}, 
    {'hanaga': 'דרום', 'shevet': 'אופק','code':'ecStOA'}, 
    {'hanaga': 'דרום', 'shevet': 'איתן','code':'jYi7Jb'}, 
    {'hanaga': 'דרום', 'shevet': 'אשל','code':'QELVFR'}, 
    {'hanaga': 'דרום', 'shevet': 'במדבר','code':'glWjbC'}, 
    {'hanaga': 'דרום', 'shevet': 'חצרים','code':'spl7h7'}, 
    {'hanaga': 'דרום', 'shevet': 'יואב','code':'Gqly6E'}, 
    {'hanaga': 'דרום', 'shevet': 'מצדה','code':'telaDt'}, 
    {'hanaga': 'דרום', 'shevet': 'נגב','code':'x1H1c3'}, 
    {'hanaga': 'דרום', 'shevet': 'נועם','code':'lNAmME'}, 
    {'hanaga': 'דרום', 'shevet': 'נופר','code':'aip4iy'}, 
    {'hanaga': 'דרום', 'shevet': 'ניצני הנגב','code':'yQzJpY'}, 
    {'hanaga': 'דרום', 'shevet': 'נמרוד','code':'FCU4ym'}, 
    {'hanaga': 'דרום', 'shevet': 'סיני','code':'nd3hpl'}, 
    {'hanaga': 'דרום', 'shevet': 'ערבה','code':'Od6EG3'}, 
    {'hanaga': 'דרום', 'shevet': 'צוק','code':'aTJxYk'}, 
    {'hanaga': 'דרום', 'shevet': 'צחור','code':'eHTxIO'}, 
    {'hanaga': 'דרום', 'shevet': 'רכסים','code':'KjIAdY'}, 
    {'hanaga': 'דרום', 'shevet': 'שגיא','code':'degAd9'}, 
    {'hanaga': 'דרום', 'shevet': 'שמשון','code':'beQCQA'}, 
    {'hanaga': 'דרום', 'shevet': 'שקד','code':'smTuTX'},  
    {'hanaga': 'דרור', 'shevet': 'בזק','code':'AFPaLN'}, 
    {'hanaga': 'דרור', 'shevet': 'בן יהודה','code':'fktqlf'}, 
    {'hanaga': 'דרור', 'shevet': 'לביא','code':'pDFvHJ'}, 
    {'hanaga': 'דרור', 'shevet': 'סירונית','code':'zbRJKI'}, 
    {'hanaga': 'דרור', 'shevet': 'פולג','code':'tBmc5U'}, 
    {'hanaga': 'דרור', 'shevet': 'רגבים','code':'0szcn3'}, 
    {'hanaga': 'דרור', 'shevet': 'רמון','code':'E1c5EH'}, 
    {'hanaga': 'דרור', 'shevet': 'תמיד','code':'x0O14r'},  
    {'hanaga': 'החוף', 'shevet': 'איתן','code':'ucfCGz'}, 
    {'hanaga': 'החוף', 'shevet': 'ארבל','code':'N40A8N'}, 
    {'hanaga': 'החוף', 'shevet': 'ארנון','code':'xFLBoO'}, 
    {'hanaga': 'החוף', 'shevet': 'דן','code':'6Gpzd4'}, 
    {'hanaga': 'החוף', 'shevet': 'הסלע צופי ים','code':'eDoZwW'}, 
    {'hanaga': 'החוף', 'shevet': 'יהודה','code':'0LRHIH'}, 
    {'hanaga': 'החוף', 'shevet': 'יעד','code':'3gkF3k'}, 
    {'hanaga': 'החוף', 'shevet': 'כנען','code':'ReHN7j'}, 
    {'hanaga': 'החוף', 'shevet': 'מכבים','code':'eWTMPz'}, 
    {'hanaga': 'החוף', 'shevet': 'משואות','code':'NNXxjk'}, 
    {'hanaga': 'החוף', 'shevet': 'מתן','code':'4aVLxW'}, 
    {'hanaga': 'החוף', 'shevet': 'עומר','code':'E9zuq4'}, 
    {'hanaga': 'החוף', 'shevet': 'עתיד','code':'o68Q0c'}, 
    {'hanaga': 'החוף', 'shevet': 'רעם','code':'KJcHIG'}, 
    {'hanaga': 'החוף', 'shevet': 'שורק','code':'BIi9aP'}, 
    {'hanaga': 'החוף', 'shevet': 'שקמה','code':'5hNFXx'},  
    {'hanaga': 'החורש', 'shevet': 'אילן','code':'1WZ6gZ'}, 
    {'hanaga': 'החורש', 'shevet': 'אלומות','code':'EKYOT4'}, 
    {'hanaga': 'החורש', 'shevet': 'אלון','code':'cN3uts'}, 
    {'hanaga': 'החורש', 'shevet': 'אלמוג','code':'RBlDf7'}, 
    {'hanaga': 'החורש', 'shevet': 'בני היער','code':'dtIQbl'}, 
    {'hanaga': 'החורש', 'shevet': 'גולן','code':'NjaZVy'}, 
    {'hanaga': 'החורש', 'shevet': 'גפן','code':'4Hr7j6'}, 
    {'hanaga': 'החורש', 'shevet': 'החלוץ','code':'UuBj1k'}, 
    {'hanaga': 'החורש', 'shevet': 'מגל','code':'HDOfGV'}, 
    {'hanaga': 'החורש', 'shevet': 'עומר','code':'xJtTZe'}, 
    {'hanaga': 'החורש', 'shevet': 'פלג','code':'vTDzwx'}, 
    {'hanaga': 'החורש', 'shevet': 'צוקים','code':'oYQtYc'}, 
    {'hanaga': 'החורש', 'shevet': 'שקד','code':'l0e4En'},  
    {'hanaga': 'הצוק', 'shevet': 'איתן','code':'3NY3lK'}, 
    {'hanaga': 'הצוק', 'shevet': 'ארד','code':'KcmEB8'}, 
    {'hanaga': 'הצוק', 'shevet': 'געש','code':'oCTJuY'}, 
    {'hanaga': 'הצוק', 'shevet': 'דקר','code':'CckNY0'}, 
    {'hanaga': 'הצוק', 'shevet': 'הרצל','code':'PBlVWk'}, 
    {'hanaga': 'הצוק', 'shevet': 'נוה מגן','code':'aOupdJ'}, 
    {'hanaga': 'הצוק', 'shevet': 'ני"ר','code':'QsIJo3'}, 
    {'hanaga': 'הצוק', 'shevet': 'סער','code':'qsYZrF'}, 
    {'hanaga': 'הצוק', 'shevet': 'רשפים','code':'mNHCYv'}, 
    {'hanaga': 'הצוק', 'shevet': 'שחף','code':'zSw0iE'},  
    {'hanaga': 'השחר', 'shevet': 'אופק','code':'pkapx5'}, 
    {'hanaga': 'השחר', 'shevet': 'אפיק','code':'3rwIya'}, 
    {'hanaga': 'השחר', 'shevet': 'גלבוע','code':'DYkSvr'}, 
    {'hanaga': 'השחר', 'shevet': 'הדר','code':'Y1JL0S'}, 
    {'hanaga': 'השחר', 'shevet': 'הראל','code':'F2jwyL'}, 
    {'hanaga': 'השחר', 'shevet': 'נבו','code':'CNZO9x'}, 
    {'hanaga': 'השחר', 'shevet': 'נחשון','code':'3wSozp'}, 
    {'hanaga': 'השחר', 'shevet': 'עמירים','code':'ERQpUR'}, 
    {'hanaga': 'השחר', 'shevet': 'צור','code':'F6wMhE'}, 
    {'hanaga': 'השחר', 'shevet': 'רכ"ס','code':'nL0HuA'}, 
    {'hanaga': 'השחר', 'shevet': 'שליט','code':'xFUT0A'},  
    {'hanaga': 'חיפה', 'shevet': 'אורן','code':'5wl7Ur'}, 
    {'hanaga': 'חיפה', 'shevet': 'אילנות','code':'5wsYWf'}, 
    {'hanaga': 'חיפה', 'shevet': 'אפיק','code':'jcA1Yc'}, 
    {'hanaga': 'חיפה', 'shevet': 'גלים','code':'5uLeOK'}, 
    {'hanaga': 'חיפה', 'shevet': 'דרור','code':'t5qnZO'}, 
    {'hanaga': 'חיפה', 'shevet': 'העגן','code':'SYDFu4'}, 
    {'hanaga': 'חיפה', 'shevet': 'חופים','code':'br2Wte'}, 
    {'hanaga': 'חיפה', 'shevet': 'כרמל','code':'OlMlWv'}, 
    {'hanaga': 'חיפה', 'shevet': 'לטם','code':'d8aoOf'}, 
    {'hanaga': 'חיפה', 'shevet': 'מגשים','code':'41uHnh'}, 
    {'hanaga': 'חיפה', 'shevet': 'משוטטים','code':'ZwoLOH'}, 
    {'hanaga': 'חיפה', 'shevet': 'נשרים','code':'3c1DOW'}, 
    {'hanaga': 'חיפה', 'shevet': 'עמית','code':'nTJa3c'}, 
    {'hanaga': 'חיפה', 'shevet': 'צופי ים חיפה','code':''}, 
    {'hanaga': 'חיפה', 'shevet': 'צופית','code':'iAvdXl'}, 
    {'hanaga': 'חיפה', 'shevet': 'תדהר','code':'u31p4Y'},  
    {'hanaga': 'יהודה', 'shevet': 'אופק','code':'RQXBrV'}, 
    {'hanaga': 'יהודה', 'shevet': 'איתן','code':'qdcmWd'}, 
    {'hanaga': 'יהודה', 'shevet': 'אליאב','code':'HcY3Mj'}, 
    {'hanaga': 'יהודה', 'shevet': 'דקר','code':'5SdJ4D'}, 
    {'hanaga': 'יהודה', 'shevet': 'האלה','code':'xqO1tC'}, 
    {'hanaga': 'יהודה', 'shevet': 'הראל','code':'EvvnyR'}, 
    {'hanaga': 'יהודה', 'shevet': 'זאב','code':'IC6fBf'}, 
    {'hanaga': 'יהודה', 'shevet': 'יהודה','code':'GO0J1g'}, 
    {'hanaga': 'יהודה', 'shevet': 'יונתן','code':'dENOWe'}, 
    {'hanaga': 'יהודה', 'shevet': 'לביא','code':'dTG2nb'}, 
    {'hanaga': 'יהודה', 'shevet': 'ערבה','code':'rtIBnG'}, 
    {'hanaga': 'יהודה', 'shevet': 'פסגות','code':'LzATfD'}, 
    {'hanaga': 'יהודה', 'shevet': 'רועי','code':'oFUEvn'}, 
    {'hanaga': 'יהודה', 'shevet': 'שוב"ל','code':'iQwy2R'}, 
    {'hanaga': 'יהודה', 'shevet': 'שורק','code':'0mAoZo'}, 
    {'hanaga': 'יהודה', 'shevet': 'תמיר','code':'nkedRK'},  
    {'hanaga': 'ירושלים', 'shevet': 'אלעד','code':'4lcpBz'}, 
    {'hanaga': 'ירושלים', 'shevet': 'אמיר','code':'J6UNAe'}, 
    {'hanaga': 'ירושלים', 'shevet': 'אריאל','code':'njRPS6'}, 
    {'hanaga': 'ירושלים', 'shevet': 'בית הכרם','code':'qMgJEk'}, 
    {'hanaga': 'ירושלים', 'shevet': 'היובל','code':'q8NKMC'}, 
    {'hanaga': 'ירושלים', 'shevet': 'העומר','code':'LBpAOI'}, 
    {'hanaga': 'ירושלים', 'shevet': 'הר חומה','code':'oLK9wK'}, 
    {'hanaga': 'ירושלים', 'shevet': 'זוהר','code':'sUlJcN'}, 
    {'hanaga': 'ירושלים', 'shevet': 'להבות','code':'KJOEyu'}, 
    {'hanaga': 'ירושלים', 'shevet': 'מודיעין','code':'1nSiOs'}, 
    {'hanaga': 'ירושלים', 'shevet': 'מצדה','code':'N5oeA3'}, 
    {'hanaga': 'ירושלים', 'shevet': 'משואות','code':'366ahn'}, 
    {'hanaga': 'ירושלים', 'shevet': 'עוז','code':'Ef5BRo'}, 
    {'hanaga': 'ירושלים', 'shevet': 'קטמונים','code':'TGqkPY'}, 
    {'hanaga': 'ירושלים', 'shevet': 'רכסים','code':'9SuOwc'}, 
    {'hanaga': 'צפון', 'shevet': 'ים','code':'4dY2Jh'}, 
    {'hanaga': 'צפון', 'shevet': 'אדיס','code':'2y8tt4'}, 
    {'hanaga': 'צפון', 'shevet': 'איריס','code':'zhXihP'}, 
    {'hanaga': 'צפון', 'shevet': 'אלון','code':'vGlT1F'}, 
    {'hanaga': 'צפון', 'shevet': 'אשחר','code':'zMoUSG'}, 
    {'hanaga': 'צפון', 'shevet': 'גונן','code':'rNlqF8'}, 
    {'hanaga': 'צפון', 'shevet': 'גלעד','code':'bJ3FCv'}, 
    {'hanaga': 'צפון', 'shevet': 'יבנאל','code':'85flHT'}, 
    {'hanaga': 'צפון', 'shevet': 'יזרעאל','code':'H7vkta'}, 
    {'hanaga': 'צפון', 'shevet': 'כנרת צופי ים','code':'2yxGQl'}, 
    {'hanaga': 'צפון', 'shevet': 'כרם','code':'US62i3'}, 
    {'hanaga': 'צפון', 'shevet': 'לביא','code':'k1uocm'}, 
    {'hanaga': 'צפון', 'shevet': 'להבות','code':'PDdYaF'}, 
    {'hanaga': 'צפון', 'shevet': 'מעיינות','code':'FAu3qk'}, 
    {'hanaga': 'צפון', 'shevet': 'עידן','code':'j7UW9l'}, 
    {'hanaga': 'צפון', 'shevet': 'עמיחי','code':'N3amc6'}, 
    {'hanaga': 'צפון', 'shevet': 'עפר','code':'TvY21o'}, 
    {'hanaga': 'צפון', 'shevet': 'שחר','code':'YhCzi8'}, 
    {'hanaga': 'צפון', 'shevet': 'שלהבת','code':'U8umbD'}, 
    {'hanaga': 'צפון', 'shevet': 'עונות','code':'WtfLcd'}, 
    {'hanaga': 'צפון', 'shevet': 'רועי','code':'2VLpCP'}, 
    {'hanaga': 'רמת גן', 'shevet': 'אילת','code':'Wse7yf'}, 
    {'hanaga': 'רמת גן', 'shevet': 'אפעל','code':'hy2eK0'}, 
    {'hanaga': 'רמת גן', 'shevet': 'ירדן','code':'TVjRIQ'}, 
    {'hanaga': 'רמת גן', 'shevet': 'ירקון','code':'ygBrN6'}, 
    {'hanaga': 'רמת גן', 'shevet': 'עלית','code':'loSre9'}, 
    {'hanaga': 'רמת גן', 'shevet': 'רמת גן','code':'ISNu8z'}, 
    {'hanaga': 'רמת גן', 'shevet': 'רמת חן','code':'c1hxk0'}, 
    {'hanaga': 'רמת גן', 'shevet': 'רעים','code':'3MTcwn'}, 
    {'hanaga': 'רמת גן', 'shevet': 'שקמה','code':'MJyV56'},  
    {'hanaga': 'שורק', 'shevet': 'אביב','code':'DxwAgM'}, 
    {'hanaga': 'שורק', 'shevet': 'איתן','code':'uMaxXw'}, 
    {'hanaga': 'שורק', 'shevet': 'אריות','code':'wEw0QC'}, 
    {'hanaga': 'שורק', 'shevet': 'גיא','code':'tqjgmu'}, 
    {'hanaga': 'שורק', 'shevet': 'דותן','code':'Vbx9hb'}, 
    {'hanaga': 'שורק', 'shevet': 'הנחל','code':'9vTtQx'}, 
    {'hanaga': 'שורק', 'shevet': 'יאיר','code':'EV6Y4C'}, 
    {'hanaga': 'שורק', 'shevet': 'ירדן','code':'rm6Bvy'}, 
    {'hanaga': 'שורק', 'shevet': 'כפיר','code':'Guk237'}, 
    {'hanaga': 'שורק', 'shevet': 'מידב','code':'lGSyWp'}, 
    {'hanaga': 'שורק', 'shevet': 'סהר','code':'rA9lBt'}, 
    {'hanaga': 'שורק', 'shevet': 'סער','code':'UjeVKu'}, 
    {'hanaga': 'שורק', 'shevet': 'עידן','code':'3wp3Y2'}, 
    {'hanaga': 'שורק', 'shevet': 'ראם','code':'cboZ5n'}, 
    {'hanaga': 'שורק', 'shevet': 'רעות','code':'DUZs7r'}, 
    {'hanaga': 'שורק', 'shevet': 'שחר','code':'4wpdmx'}, 
    {'hanaga': 'שורק', 'shevet': 'שלהבות','code':'9ojCdk'}, 
    {'hanaga': 'שורק', 'shevet': 'שני"ר','code':'gknbtv'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'אביב','code':'ol9Gik'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'אופק','code':'CWcSe1'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'איתן','code':'JtyVUq'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'בית דני','code':'OODZ5z'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'דיזנגוף','code':'ngP15b'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'דן','code':'moaFOY'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'הגבעה','code':'DTKJa7'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'החורש','code':'X7W0Ji'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'הנשיא','code':'PARTwS'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'הצוק','code':'ZF1OF5'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'חורב','code':'V7nCZ7'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'חצב','code':'5s9T8K'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'יפו','code':'KUCZpd'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'כפיר','code':'Pt37WW'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'צבר','code':'j97kQB'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'צהלה','code':'wwUKV2'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'צופי ים יפו','code':'R3ZZZV'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'צופי ים תל אביב','code':'D6nwoa'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'קהילה','code':'rjRCvv'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': "רמת אביב ג'",'code':'w6GGCB'}, 
    {'hanaga': 'תל אביב יפו', 'shevet': 'רעות','code':'kLdjbf'}
]


